"""
Book configuration — maps book IDs to their data paths and metadata.
"""

BOOKS = {
    "pride_and_prejudice": {
        "title": "Pride and Prejudice",
        "author": "Jane Austen",
        "culture": "English",
        "path_pattern": "batch_overnight/pride_and_prejudice/batch_*/merged_blocks.jsonl",
        "protagonist": "Elizabeth",
        "protagonist_aliases": ["Elizabeth", "Elizabeth Bennet", "Eliza", "Lizzy"],
        "character_aliases": {
            "Mr. Darcy": ["Mr. Darcy", "Darcy", "Fitzwilliam Darcy"],
            "Elizabeth": ["Elizabeth", "Elizabeth Bennet", "Eliza", "Lizzy"],
            "Mr. Bingley": ["Mr. Bingley", "Bingley", "Charles Bingley"],
            "Jane": ["Jane", "Jane Bennet", "Miss Bennet"],
            "Mrs. Bennet": ["Mrs. Bennet"],
            "Mr. Bennet": ["Mr. Bennet"],
            "Wickham": ["Wickham", "Mr. Wickham", "George Wickham"],
            "Lydia": ["Lydia", "Lydia Bennet"],
            "Lady Catherine": ["Lady Catherine", "Lady Catherine de Bourgh"],
            "Mr. Collins": ["Mr. Collins", "Collins"],
            "Charlotte": ["Charlotte", "Charlotte Lucas", "Mrs. Collins"],
        },
        "phantom_characters": ["Dantes", "the Emperor", "Edmond"],
    },
    "crime_and_punishment": {
        "title": "Crime and Punishment",
        "author": "Fyodor Dostoevsky",
        "culture": "Russian",
        "path_pattern": "batch_overnight/crime_and_punishment/batch_*/merged_blocks.jsonl",
        "protagonist": "Raskolnikov",
        "protagonist_aliases": ["Raskolnikov", "Rodya", "Rodion", "the young man", "the main actor", "young man", "young_man", "actor", "unknown_actor", "Rodion Romanovitch Raskolnikov"],
        "character_aliases": {
            "Raskolnikov": ["Raskolnikov", "Rodya", "Rodion", "the young man", "the main actor", "young man", "young_man", "actor", "unknown_actor", "Rodion Romanovitch Raskolnikov"],
            "Sonya": ["Sonia", "Sonya", "Sofya Semyonovna", "Sofya"],
            "Razumikhin": ["Razumihin", "Razumikhin"],
            "Porfiry": ["Porfiry", "Porfiry Petrovitch"],
            "Dunya": ["Dounia", "Dunya", "Avdotya Romanovna"],
            "Svidrigailov": ["Svidrigailov", "Svidrigailov Arkady Ivanovitch"],
            "Marmeladov": ["Marmeladov"],
            "Katerina Ivanovna": ["Katerina Ivanovna"],
            "Luzhin": ["Luzhin", "Pyotr Petrovitch"],
        },
        "phantom_characters": [],
    },
    "les_miserables": {
        "title": "Les Mis\u00e9rables",
        "author": "Victor Hugo",
        "culture": "French",
        "path_pattern": "batch_overnight/les_miserables/batch_*/merged_blocks.jsonl",
        "protagonist": "Valjean",
        "protagonist_aliases": ["Valjean", "Jean Valjean", "M. Madeleine", "the convict", "the man"],
        "character_aliases": {
            "Valjean": ["Valjean", "Jean Valjean", "M. Madeleine", "the convict", "the man"],
            "Bishop Myriel": ["M. Myriel", "M. Charles Myriel", "the Bishop", "Bishop Myriel", "Monseigneur Bienvenu"],
            "Javert": ["Javert"],
            "Fantine": ["Fantine"],
            "Cosette": ["Cosette"],
            "Marius": ["Marius"],
            "Thenardier": ["Thenardier", "Th\u00e9nardier"],
        },
        "phantom_characters": [],
    },
    "monte_cristo": {
        "title": "The Count of Monte Cristo",
        "author": "Alexandre Dumas",
        "culture": "French",
        "path_pattern": "monte_cristo/run_20260204_140822/merged_blocks.jsonl",
        "protagonist": "Dant\u00e8s",
        "protagonist_aliases": ["Dant\u00e8s", "Dantes", "Edmond", "Edmond Dant\u00e8s", "the young man", "young man", "young sailor"],
        "character_aliases": {
            "Dant\u00e8s": ["Dant\u00e8s", "Dantes", "Edmond", "Edmond Dant\u00e8s", "the young man", "young man", "young sailor"],
            "Fernand": ["Fernand", "Fernand Mondego"],
            "Danglars": ["Danglars"],
            "Villefort": ["Villefort", "the deputy"],
            "Merc\u00e9d\u00e8s": ["Merc\u00e9d\u00e8s", "Mercedes", "the Catalan"],
            "Abb\u00e9 Faria": ["Faria", "Abb\u00e9 Faria", "the abb\u00e9"],
            "M. Morrel": ["M. Morrel", "Morrel", "owner"],
        },
        "phantom_characters": [],
    },
    "tale_of_genji": {
        "title": "The Tale of Genji",
        "author": "Murasaki Shikibu",
        "culture": "Japanese",
        "path_pattern": "shakespear/the_tale_of_genji/cheap_the_tale_of_genji/merged_blocks.jsonl",
        "protagonist": "Genji",
        "protagonist_aliases": ["Genji", "the Shining Prince", "Prince Genji"],
        "character_aliases": {
            "Genji": ["Genji", "the Shining Prince", "Prince Genji"],
            "Fujitsubo": ["Fujitsubo", "Lady Fujitsubo"],
            "Aoi": ["Aoi", "Lady Aoi"],
            "Murasaki": ["Murasaki", "young Murasaki"],
            "Emperor": ["Emperor", "the Emperor"],
            "Lady Rokuj\u014d": ["Lady Rokuj\u014d", "Rokuj\u014d"],
            "Lady K\u014dkiden": ["Lady K\u014dkiden", "K\u014dkiden"],
        },
        "phantom_characters": [],
    },
    "hamlet": {
        "title": "Hamlet",
        "author": "William Shakespeare",
        "culture": "Elizabethan",
        "path_pattern": "shakespeare_batch/hamlet/batch_*/merged_blocks.jsonl",
        "protagonist": "Hamlet",
        "protagonist_aliases": ["Hamlet", "Prince Hamlet"],
        "character_aliases": {
            "Hamlet": ["Hamlet", "Prince Hamlet", "HAMLET"],
            "Claudius": ["Claudius", "King Claudius", "the King", "CLAUDIUS", "King"],
            "Gertrude": ["Gertrude", "Queen Gertrude", "the Queen", "GERTRUDE", "Queen"],
            "Ophelia": ["Ophelia", "OPHELIA"],
            "Horatio": ["Horatio", "HORATIO"],
            "Laertes": ["Laertes", "LAERTES"],
            "Polonius": ["Polonius", "POLONIUS"],
            "Ghost": ["Ghost", "the Ghost", "GHOST"],
        },
        "phantom_characters": [],
    },
    "macbeth": {
        "title": "Macbeth",
        "author": "William Shakespeare",
        "culture": "Elizabethan",
        "path_pattern": "shakespeare_batch/macbeth/batch_*/merged_blocks.jsonl",
        "protagonist": "Macbeth",
        "protagonist_aliases": ["Macbeth", "MACBETH"],
        "character_aliases": {
            "Macbeth": ["Macbeth", "MACBETH"],
            "Lady Macbeth": ["Lady Macbeth", "LADY MACBETH"],
            "Duncan": ["Duncan", "DUNCAN", "King Duncan"],
            "Banquo": ["Banquo", "BANQUO"],
            "Macduff": ["Macduff", "MACDUFF"],
            "Malcolm": ["Malcolm", "MALCOLM"],
            "Witches": ["Witches", "the Witches", "Three Witches"],
            "Ross": ["Ross", "ROSS"],
        },
        "phantom_characters": [],
    },
    "othello": {
        "title": "Othello",
        "author": "William Shakespeare",
        "culture": "Elizabethan",
        "path_pattern": "shakespeare_batch/othello/batch_*/merged_blocks.jsonl",
        "protagonist": "Othello",
        "protagonist_aliases": ["Othello", "the Moor"],
        "character_aliases": {
            "Othello": ["Othello", "the Moor", "OTHELLO"],
            "Iago": ["Iago", "IAGO"],
            "Desdemona": ["Desdemona", "DESDEMONA"],
            "Cassio": ["Cassio", "Michael Cassio", "CASSIO"],
            "Emilia": ["Emilia", "EMILIA"],
            "Roderigo": ["Roderigo", "RODERIGO"],
            "Brabantio": ["Brabantio", "BRABANTIO"],
        },
        "phantom_characters": [],
    },
    "romeo_and_juliet": {
        "title": "Romeo and Juliet",
        "author": "William Shakespeare",
        "culture": "Elizabethan",
        "path_pattern": "shakespeare_batch/romeo_and_juliet/batch_*/merged_blocks.jsonl",
        "protagonist": "Romeo",
        "protagonist_aliases": ["Romeo"],
        "character_aliases": {
            "Romeo": ["Romeo", "ROMEO"],
            "Juliet": ["Juliet", "JULIET"],
            "Tybalt": ["Tybalt", "TYBALT"],
            "Mercutio": ["Mercutio", "MERCUTIO"],
            "Benvolio": ["Benvolio", "BENVOLIO"],
            "Friar Laurence": ["Friar Laurence", "Friar Lawrence", "the Friar", "FRIAR LAURENCE"],
            "Nurse": ["Nurse", "the Nurse", "NURSE"],
            "Capulet": ["Capulet", "Lord Capulet", "CAPULET"],
            "Prince": ["Prince", "Prince Escalus", "PRINCE"],
            "Lady Capulet": ["Lady Capulet", "LADY CAPULET"],
            "Paris": ["Paris", "PARIS"],
        },
        "phantom_characters": [],
    },
    "the_tempest": {
        "title": "The Tempest",
        "author": "William Shakespeare",
        "culture": "Elizabethan",
        "path_pattern": "shakespeare_batch/the_tempest/batch_*/merged_blocks.jsonl",
        "protagonist": "Prospero",
        "protagonist_aliases": ["Prospero"],
        "character_aliases": {
            "Prospero": ["Prospero"],
            "Miranda": ["Miranda"],
            "Ariel": ["Ariel"],
            "Caliban": ["Caliban"],
            "Ferdinand": ["Ferdinand"],
            "Antonio": ["Antonio"],
            "Gonzalo": ["Gonzalo"],
            "Sebastian": ["Sebastian"],
            "Alonso": ["Alonso"],
        },
        "phantom_characters": [],
    },
    # ── Batch 1 books (not previously in dashboard) ─────────────────────
    "anna_karenina": {
        "title": "Anna Karenina",
        "author": "Leo Tolstoy",
        "culture": "Russian",
        "path_pattern": "batch_overnight/anna_karenina/batch_*/merged_blocks.jsonl",
        "protagonist": "Levin",
        "protagonist_aliases": ["Levin", "Konstantin Levin"],
        "character_aliases": {
            "Levin": ["Levin", "Konstantin Levin"],
            "Anna": ["Anna", "Madame Karenina", "Anna Karenina"],
            "Oblonsky": ["Stepan Arkadyevitch", "Oblonsky", "Stiva"],
            "Vronsky": ["Vronsky", "Count Vronsky"],
            "Kitty": ["Kitty", "Princess Kitty"],
            "Dolly": ["Dolly", "Darya Alexandrovna"],
            "Karenin": ["Karenin", "Alexei Alexandrovich"],
            "Sergey Ivanovitch": ["Sergey Ivanovitch"],
        },
        "phantom_characters": ["the Emperor", "unknown_actor"],
    },
    "jane_eyre": {
        "title": "Jane Eyre",
        "author": "Charlotte Bront\u00eb",
        "culture": "English",
        "path_pattern": "batch_overnight/jane_eyre/batch_*/merged_blocks.jsonl",
        "protagonist": "Jane",
        "protagonist_aliases": ["Jane", "Jane Eyre", "the narrator", "I", "the main actor"],
        "character_aliases": {
            "Jane": ["Jane", "Jane Eyre", "the narrator", "I", "the main actor"],
            "Mr. Rochester": ["Mr. Rochester", "Rochester", "the gentleman", "the man"],
            "St. John": ["St. John", "St. John Rivers"],
            "Adele": ["Adele", "Ad\u00e8le"],
            "Mrs. Fairfax": ["Mrs. Fairfax"],
            "Diana": ["Diana", "Diana Rivers"],
            "Bessie": ["Bessie"],
            "Mrs. Reed": ["Mrs. Reed"],
        },
        "phantom_characters": ["the Emperor", "unknown_actor", "the speaker"],
    },
    "wuthering_heights": {
        "title": "Wuthering Heights",
        "author": "Emily Bront\u00eb",
        "culture": "English",
        "path_pattern": "batch_overnight/wuthering_heights/batch_*/merged_blocks.jsonl",
        "protagonist": "Heathcliff",
        "protagonist_aliases": ["Heathcliff", "Mr. Heathcliff"],
        "character_aliases": {
            "Heathcliff": ["Heathcliff", "Mr. Heathcliff"],
            "Catherine": ["Catherine", "Cathy"],
            "Edgar Linton": ["Linton", "Mr. Linton", "Edgar Linton", "Edgar"],
            "Nelly": ["Nelly", "Ellen", "Ellen Dean"],
            "Hareton": ["Hareton", "Hareton Earnshaw"],
            "Hindley": ["Hindley"],
            "Isabella": ["Isabella"],
            "Joseph": ["Joseph"],
        },
        "phantom_characters": ["the Emperor", "the narrator", "the main actor", "unknown_actor", "the speaker"],
    },
    "the_iliad": {
        "title": "The Iliad",
        "author": "Homer",
        "culture": "Ancient Greek",
        "path_pattern": "batch_overnight/the_iliad/batch_*/merged_blocks.jsonl",
        "protagonist": "Hector",
        "protagonist_aliases": ["Hector"],
        "character_aliases": {
            "Hector": ["Hector"],
            "Achilles": ["Achilles", "Pelides"],
            "Ulysses": ["Ulysses", "Odysseus"],
            "Agamemnon": ["Agamemnon", "Atrides", "the king"],
            "Diomedes": ["Tydides", "Diomed", "Diomedes"],
            "Ajax": ["Ajax"],
            "Nestor": ["Nestor"],
            "Paris": ["Paris", "Alexander"],
            "Juno": ["Juno"],
            "Jove": ["Jove", "Jupiter"],
            "Menelaus": ["Menelaus"],
        },
        "phantom_characters": ["the chief", "unknown_actor", "the speaker"],
    },
    # ── New Gutenberg batch books ────────────────────────────────────────
    "treasure_island": {
        "title": "Treasure Island",
        "author": "Robert Louis Stevenson",
        "culture": "English",
        "path_pattern": "batch_overnight/120_treasure_island/batch_*/merged_blocks.jsonl",
        "protagonist": "Jim",
        "protagonist_aliases": ["Jim", "Jim Hawkins", "the narrator", "I"],
        "character_aliases": {
            "Jim": ["Jim", "Jim Hawkins", "the narrator", "I"],
            "Silver": ["Silver", "Long John", "Long John Silver", "John Silver"],
            "Captain Smollett": ["Captain Smollett", "the captain"],
            "Dr. Livesey": ["Dr. Livesey", "the doctor"],
            "Squire Trelawney": ["the squire", "Squire Trelawney"],
            "Ben Gunn": ["Ben Gunn"],
        },
        "phantom_characters": ["unknown_actor", "the speaker", "the main actor"],
    },
    "call_of_the_wild": {
        "title": "The Call of the Wild",
        "author": "Jack London",
        "culture": "American",
        "path_pattern": "batch_overnight/215_cover/batch_*/merged_blocks.jsonl",
        "protagonist": "Buck",
        "protagonist_aliases": ["Buck", "the dog"],
        "character_aliases": {
            "Buck": ["Buck", "the dog"],
            "John Thornton": ["John Thornton", "Thornton"],
            "Spitz": ["Spitz"],
            "Hal": ["Hal"],
            "Mercedes": ["Mercedes"],
            "Francois": ["Francois", "Fran\u00e7ois"],
            "Perrault": ["Perrault"],
            "Dave": ["Dave"],
            "Charles": ["Charles"],
        },
        "phantom_characters": ["unknown_actor", "the speaker"],
    },
    "moby_dick": {
        "title": "Moby-Dick",
        "author": "Herman Melville",
        "culture": "American",
        "path_pattern": "batch_overnight/2701_moby-dick/batch_*/merged_blocks.jsonl",
        "protagonist": "Ahab",
        "protagonist_aliases": ["Ahab", "Captain Ahab", "the Captain"],
        "character_aliases": {
            "Ahab": ["Ahab", "Captain Ahab", "the Captain"],
            "Ishmael": ["Ishmael", "the narrator", "I"],
            "Queequeg": ["Queequeg"],
            "Starbuck": ["Starbuck"],
            "Stubb": ["Stubb"],
            "Flask": ["Flask"],
            "Tashtego": ["Tashtego"],
            "Steelkilt": ["Steelkilt"],
        },
        "phantom_characters": ["unknown_actor", "the speaker", "the main actor", "the crew"],
    },
    "the_odyssey": {
        "title": "The Odyssey",
        "author": "Homer",
        "culture": "Ancient Greek",
        "path_pattern": "batch_overnight/1727_illustration/batch_*/merged_blocks.jsonl",
        "protagonist": "Ulysses",
        "protagonist_aliases": ["Ulysses", "Odysseus"],
        "character_aliases": {
            "Ulysses": ["Ulysses", "Odysseus"],
            "Telemachus": ["Telemachus"],
            "Penelope": ["Penelope"],
            "Eumaeus": ["Eumaeus"],
            "Minerva": ["Minerva", "Athena"],
            "Antinous": ["Antinous"],
            "Menelaus": ["Menelaus"],
            "Eurymachus": ["Eurymachus"],
            "Euryclea": ["Euryclea"],
            "Nestor": ["Nestor"],
        },
        "phantom_characters": ["the speaker", "the narrator", "unknown_actor", "the main actor", "the author", "the translator"],
    },
    "the_aeneid": {
        "title": "The Aeneid",
        "author": "Virgil",
        "culture": "Ancient Roman",
        "path_pattern": "batch_overnight/227_publi_vergili_maronis/batch_*/merged_blocks.jsonl",
        "protagonist": "Aeneas",
        "protagonist_aliases": ["Aeneas", "Aeneae"],
        "character_aliases": {
            "Aeneas": ["Aeneas", "Aeneae"],
            "Turnus": ["Turnus"],
            "Dido": ["Dido"],
            "Latinus": ["Latinus"],
            "Juno": ["Iuno", "Juno"],
            "Venus": ["Venus"],
            "Anchises": ["Anchises"],
            "Camilla": ["Camilla"],
            "Euryalus": ["Euryalus"],
            "Nisus": ["Nisus"],
            "Pallas": ["Pallas"],
        },
        "phantom_characters": ["unknown_actor", "the speaker"],
    },
    "metamorphoses": {
        "title": "Metamorphoses",
        "author": "Ovid",
        "culture": "Ancient Roman",
        "path_pattern": "batch_overnight/26073_transcribers_note/batch_*/merged_blocks.jsonl",
        "protagonist": "Hercules",
        "protagonist_aliases": ["Hercules"],
        "character_aliases": {
            "Hercules": ["Hercules"],
            "Ulysses": ["Ulysses"],
            "Achilles": ["Achilles"],
            "Aeneas": ["Aeneas", "\u00c6neas"],
            "Orpheus": ["Orpheus"],
            "Venus": ["Venus"],
            "Peleus": ["Peleus"],
            "Iphis": ["Iphis"],
            "Halcyone": ["Halcyone"],
            "Ceyx": ["Ceyx"],
            "Ajax": ["Ajax"],
            "Theseus": ["Theseus"],
        },
        "phantom_characters": ["unknown_actor", "the speaker", "the lady", "the narrator"],
    },
    "scarlet_letter": {
        "title": "The Scarlet Letter",
        "author": "Nathaniel Hawthorne",
        "culture": "American",
        "path_pattern": "batch_overnight/33_the_scarlet_letter/batch_*/merged_blocks.jsonl",
        "protagonist": "Hester",
        "protagonist_aliases": ["Hester", "Hester Prynne"],
        "character_aliases": {
            "Hester": ["Hester", "Hester Prynne"],
            "Dimmesdale": ["Mr. Dimmesdale", "Reverend Mr. Dimmesdale", "Arthur Dimmesdale", "the minister", "the clergyman"],
            "Chillingworth": ["Roger Chillingworth", "the physician"],
            "Pearl": ["Pearl"],
            "Governor Bellingham": ["Governor Bellingham"],
            "Mistress Hibbins": ["Mistress Hibbins"],
            "Mr. Wilson": ["Mr. Wilson"],
        },
        "phantom_characters": ["the narrator", "unknown_actor", "the speaker"],
    },
    "arabian_nights": {
        "title": "The Arabian Nights",
        "author": "Traditional (Burton trans.)",
        "culture": "Middle Eastern",
        "path_pattern": "batch_overnight/3435_the_book_of_the/batch_*/merged_blocks.jsonl",
        "protagonist": "Shahrazad",
        "protagonist_aliases": ["Shahrazad", "Scheherazade", "the narrator"],
        "character_aliases": {
            "Shahrazad": ["Shahrazad", "Scheherazade", "the narrator"],
            "The King": ["the King", "the Sultan", "the Caliph"],
            "The Wazir": ["the Wazir"],
            "The Barber": ["the Barber"],
            "The Porter": ["the Porter"],
            "Badr al-Din Hasan": ["Badr al-Din Hasan"],
            "Ajib": ["Ajib"],
            "The Ifrit": ["the Ifrit"],
        },
        "phantom_characters": ["unknown_actor", "the speaker", "the main actor", "the lady", "the young man", "the youth"],
    },
}

CULTURE_COLORS = {
    "French": "#3B82F6",
    "English": "#22C55E",
    "Russian": "#EF4444",
    "Japanese": "#A855F7",
    "Elizabethan": "#EAB308",
    "American": "#F97316",
    "Ancient Greek": "#06B6D4",
    "Ancient Roman": "#8B5CF6",
    "Middle Eastern": "#D946EF",
}

EMOTION_COLORS = {
    "hope": "#22C55E",
    "fear": "#4338CA",
    "anger": "#DC2626",
    "pride": "#D97706",
    "shame": "#9D174D",
    "resolve": "#6B7280",
}

EMOTIONS = ["hope", "fear", "anger", "pride", "shame", "resolve"]
BELIEFS = ["providence_conviction", "instrumental_rationalization", "suspicion_paranoia", "identity_stability"]
